### ISSUE TITLE
Compiler error,Can you help me?

### ISSUE THREAD

**Issue by AlphabugX** [Bl0omZ/JNDIEXP#1]
Can you Help me?

- JDK 1.8
- mvn
- CentOS

`mvn compile`

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/27001865/195125870-a320d5b7-0cf7-4e50-804c-4c8a511a19d4.png">

**Comment by Bl0omZ** [comment]
try `mvn package '-Dmaven.test.skip=true'`
