### ISSUE TITLE
很多payload会报错是什么原因

### ISSUE THREAD

**Issue by ymbzd** [Bl0omZ/JNDIEXP#3]
![image](https://github.com/Bl0omZ/JNDIEXP/assets/39881690/7d60a70b-d447-4c64-b16a-fe1e7ed7c4f1)

**Comment by Bl0omZ** [comment]
下载编译好的jar包
可以试试fuzz2/rome/dnslog 或者
ldap://0.0.0.0:1389/fuzzbyDNS/[domain]
