### ISSUE TITLE
这些利用链都可以绕过8u191以上的限制吗？

### ISSUE THREAD

**Issue by lovelyjuice** [Bl0omZ/JNDIEXP#4]
![image](https://github.com/user-attachments/assets/298c6c5d-7a41-4356-a1dd-f8f6f69a0b73)

**Comment by Bl0omZ** [comment]
> ![image](https://private-user-images.githubusercontent.com/20644461/388000045-298c6c5d-7a41-4356-a1dd-f8f6f69a0b73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTY0NjksIm5iZiI6MTczMjA5NjE2OSwicGF0aCI6Ii8yMDY0NDQ2MS8zODgwMDAwNDUtMjk4YzZjNWQtN2E0MS00MzU2LWExZGQtZjhmNmY2OWEwYjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA5NDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZmE1NmUxOTBmN2U0NGM1N2VlNWMwOWIzNzNmN2M5MjA5MDVhZTIxMzlmZDZmZGJlODlhMTA3ZDI1ZWJlMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tnGXBUc6HkxkIsNTM06TeViLdGBoBZ9SK-LdJ-G9qaI)

目标有对应的jar包就可以绕过限制
